# Copyright 2024, UNSW
# SPDX-License-Identifier: BSD-2-Clause

[target.aarch64-unknown-linux-musl]
rustflags = ["-Clinker=rust-lld"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Clinker=rust-lld"]
